### PR TITLE
Fix #304: view being cut by "non-present" navigation bar

### LINKED ISSUE #304: LG G6 "Hide Home Touch Buttons" feature cuts off bottom of view
- [X] I have verified the issue exists on the latest version
- [X] I am able to reproduce it

**Version used:** 1.12.0

**Stack trace:** LG G6 "Hide Home Touch Buttons" feature causes bottom of TapTargetView to be cut off. 
Image attached.
lg_g6_tooltip_issue
Note: Target is bottom right view.

**Android version:** 8.0.0

### PR DESCRIPTION
**Pull request by mickele**
I did some investigations regarding #304 and the reason is that Samsung (and LG apparently) report the wrong value on `DisplayMetrics#heightPixels`. Like other devices with digital navigation bar, the reported value should return the `real display height - navigation bar height` but when the "hide nav bar" feature is enabled on these devices, the display metrics still uses the, now hidden, navigation bar height in the calculation.

I don't expect vendors to change this behaviour at anytime soon since this was never an official Android feature AFAIK and not documented, so in the meanwhile we can trust the rect values for boundaries it's calculated for the parent, unless the flag `FLAG_LAYOUT_NO_LIMITS ` is set.

### CODE REVIEW

File: taptargetview/src/main/java/com/getkeepsafe/taptargetview/TapTargetView.java [hunk 1]
```diff
@@ -438,6 +438,15 @@ public TapTargetView(final Context context,
       translucentNavigationBar = false;
     }
 
+    final boolean layoutNoLimits;
```
Comment (xiphirx) [inline taptargetview/src/main/java/com/getkeepsafe/taptargetview/TapTargetView.java]: Instead of repeating this sort of code, we can merge with the previous code:

```java
final boolean hasKitkat = Build.VERSION.SDK_INT >= 19;
final boolean translucentStatusBar;
final boolean translucentNavigationBar;
final boolean layoutNoLimits;
if (context instanceof Activity) {
  final int flags = activity.getWindow().getAttributes().flags;
  translucentStatusBar = hasKitkat && (flags & WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS) != 0;
  translucentNavigationBar = hasKitkat && (flags & WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION) != 0;
  layoutNoLimits = (flags & WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS) != 0;
} else {
  ...
}
```

Comment (mickele) [reply taptargetview/src/main/java/com/getkeepsafe/taptargetview/TapTargetView.java]: Thanks for the feedback, I changed the code as requested.
Much better 👍

**Comment by mickele** [comment]
Sure, removed the other changes.

**Comment by xiphirx** [comment]
Thanks!
